### PR TITLE
v3 impelmentation

### PR DESCRIPTION
**Pull request by jsumners**
This PR fixes the long standing issue of having to detect/setup the session via the `preHandler` hook. Since Fastify v2, we can do this work at the proper `onRequest` location.

This PR also introduces a proxy object for the session object so that we can determine if the session has been modified. If the session has not been changed, we do not attempt to save it or send a useless cookie. We opted not to use the proxy in the original implementation because proxies were quite slow. Since that time, the performance of proxies has been dramatically improved and we see no reason to avoid their usage at this time.

@yotammadem please review this PR to make sure it works for you.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by yotammadem** [comment]
Impl looks good,
I see that you removed my tests and added unit tests to the session impl instead. That's fine but don't you think it will be better to also have test that makes sure that cookie is not created when session is not modified? (like the one that was deleted)

**Comment by jsumners** [comment]
@yotammadem test restored.

**Review by yotammadem — APPROVED** [review]
Thank you!

**Pull request merged**
